project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "HMK"
  favicon: images/favicon-32x32.png
  navbar:
    right:
      - publications.qmd
      - fun.qmd
  page-footer:
    left: |
      <span text-align="center" class="faux-block">&#169; 2023 Harshith Mohan Kumar CC BY-SA 4.0</span>
    right: |
      <span text-align="center" class="faux-block"><a href="mailto:mail.hiharshith18@gmail.com">Contact Me!</a></span>

format:
  html:
    from: markdown+emoji
    theme: 
      light: sandstone
      dark: [sandstone, theme-dark.scss]
    css: _sandstone.scss
    toc: true


