---
title: "Publications"
from: markdown+emoji
---

For an updated list of publications and citations, check out my [Google Scholar](https://scholar.google.com/citations?user=7hBzcg0AAAAJ&hl=en).

**Fusing Pseudo Labels with Weak Supervision for Dynamic Traffic Scenarios**  
**Harshith Mohan Kumar**, Sean Lawrence  
*ICCV 2023 BRAVO Workshop*  
<a href="https://valeoai.github.io/bravo/submissions/bravo_abstract_fusing_pseudo_labels.pdf" class="btn btn-outline-primary btn-sm">paper</a>
<a href="https://valeoai.github.io/bravo/" class="btn btn-outline-primary btn-sm">website</a>

**OCTraN: 3D Occupancy Convolutional Transformer Network in Unstructured Traffic Scenarios**  
Aditya N Ganesh, Dhruval Pobbathi Badrinath, **Harshith Mohan Kumar**, Priya S S, Surabhi Narayan  
*CVPR 2023 T4V Workshop*  
<a href="https://arxiv.org/abs/2307.10934" class="btn btn-outline-primary btn-sm">paper</a>
<a href="https://sites.google.com/view/t4v-cvpr23/papers?authuser=0" class="btn btn-outline-primary btn-sm">website</a>

**GraphCoReg: Co-Training for Regression on Temporal Graphs**  
**Harshith Mohan Kumar**, Vishruth Veerendranath, Vibha Masti, Divya Shekar, Bhaskarjyoti Das  
*ECML-PKDD 2022 MLG Workshop*  
:trophy: **Best Student Paper Award**  
<a href="https://openreview.net/pdf?id=JExuzizhS-p" class="btn btn-outline-primary btn-sm">paper</a>

**Multivariate Covid-19 Forecasting with Vaccinations as a Factor**  
Vibha Masti, Vishruth Veerendranath, **Harshith Mohan Kumar**  
*IEEE TENSYMP 2022*, also presented at *ICML 2022 Healthcare-AI Workshop*  
<a href="https://ieeexplore.ieee.org/document/9864476" class="btn btn-outline-primary btn-sm">paper</a>

**Semi-supervised Learning with In-domain Pre-training and Deep Co-training**  
Bhaskarjyoti Das, **Harshith Mohan Kumar**, Divya Shekar, Mohammed Zayd Jamadar  
*Springer ICICCT 2022*  
<a href="https://link.springer.com/chapter/10.1007/978-981-19-4960-9_49" class="btn btn-outline-primary btn-sm">paper</a>

**Classification of Recyclable Waste Generated in Indian Households**  
**Harshith MohanKumar**, Mohammed Zayd Jamadar, S Natarajan, H Nithin  
*Springer WorldS4 2021*  
<a href="https://link.springer.com/chapter/10.1007/978-981-16-6309-3_48" class="btn btn-outline-primary btn-sm">paper</a>